library(leaps)
library(car)
setwd("C:\\Users\\Antonio\\Desktop\\sda-project")
data = read.csv("covid-data.csv", header=T, sep=",")
columns <- colnames(data)
data <- data[-c(11654,11743,11747,11748,11749,11736),]
data_filtered <- data[which(data$iso_code %in% c('ITA', 'GBR', 'IND', 'JPN', 'ISR', 'LUX', 'AUS', 'AUT', 'NZL', 'ARG', 'BEL', 'CAN', 'ZAF', 'PRT')),columns[c(6,13,14,20,21,22,23,24,25,26,27,28,29,30,31)]]
data_test = data_filtered <- data[which(data$iso_code %in% c('USA','IRN','KOR','URY')),columns[c(6,13,14,20,21,22,23,24,25,26,27,28,29,30,31)]]
data_filtered = na.omit(data_filtered)

# fit a linear model with all predictors (no changes in the response)
fit = lm(new_cases~.,data_filtered)
summary(fit)
# model diagnositic plots
dev.new()
par(mfrow=c(2,2))
plot(fit)

# fit a linear model with all predictors (log of the response)
data_filtered.log <- data_filtered
data_filtered.log$new_cases <- log(data_filtered.log$new_cases + 0.1)
log.fit = lm(new_cases~.,data_filtered.log)
summary(log.fit)
# model diagnositic plots
dev.new()
par(mfrow=c(2,2))
plot(log.fit)

# fit a linear model with all predictors (sqrt of the response)
data_filtered.sqrt <- data_filtered
data_filtered.sqrt$new_cases <- sqrt(data_filtered.sqrt$new_cases)
sqrt.fit = lm(new_cases~.,data_filtered.sqrt)
summary(sqrt.fit)
# model diagnositic plots
dev.new()
par(mfrow=c(2,2))
plot(sqrt.fit)

#BESTSUBSET SELECTION
regfit.full=regsubsets(data_filtered$new_cases~.,data_filtered,nvmax = 14)
reg.summary=summary(regfit.full)
dev.new()
par(mfrow=c(2,2))
plot(reg.summary$rss ,xlab="Number of Variables ",ylab="RSS",type="l")
points(which.min(reg.summary$rss),min(reg.summary$rss), col="red",cex=2,pch=20)
plot(reg.summary$adjr2 ,xlab="Number of Variables ",
     ylab="Adjusted RSq",type="l")
points(which.max(reg.summary$adjr2),max(reg.summary$adjr2), col="red",cex=2,pch=20)
plot(reg.summary$cp ,xlab="Number of Variables ",ylab="Cp", type="l")
points(which.min(reg.summary$cp ),min(reg.summary$cp),col="red",cex=2,pch=20)
plot(reg.summary$bic ,xlab="Number of Variables ",ylab="BIC",type="l")
points(which.min(reg.summary$bic),min(reg.summary$bic),col="red",cex=2,pch=20)
dev.new()
plot(regfit.full,scale="r2")
dev.new()
plot(regfit.full,scale="adjr2")
dev.new()
plot(regfit.full,scale="Cp")
dev.new()
plot(regfit.full,scale="bic")
###model with 4 predictors
regfit.4=regsubsets(data_filtered$new_cases~.,data_filtered,nvmax = 4)
lm4 = lm(new_cases~total_tests+cvd_death_rate+male_smokers+new_tests,data_filtered)
lm4.log = lm(new_cases~total_tests+cvd_death_rate+male_smokers+new_tests,data_filtered.log)
lm4.sqrt = lm(new_cases~total_tests+cvd_death_rate+male_smokers+new_tests,data_filtered.sqrt)
dev.new()
par(mfrow=c(2,2))
plot(lm4)
plot(lm4.log)
plot(lm4.sqrt)
vif(lm4)
vif(lm4.log)
vif(lm4.sqrt)
#model with 7 predictors
regfit.10=regsubsets(data_filtered$new_cases~.,data_filtered,nvmax = 10)
lm7.log = lm(new_cases~.-stringency_index-population_density-aged_65_older-cvd_death_rate-extreme_poverty-median_age-aged_70_older,data_filtered.log)
lm7= lm(new_cases~.-stringency_index-population_density-aged_65_older-cvd_death_rate-extreme_poverty-median_age-aged_70_older,data_filtered)
lm7.sqrt = lm(new_cases~.-stringency_index-population_density-aged_65_older-cvd_death_rate-extreme_poverty-median_age-aged_70_older,data_filtered.sqrt)
dev.new()
par(mfrow=c(2,2))
plot(lm7)
plot(lm7.log)
plot(lm7.sqrt)
vif(lm7)
vif(lm7.log)
vif(lm7.sqrt)
#model with 10 predictors
lm10.log = lm(new_cases~.-stringency_index-population_density-aged_65_older-cvd_death_rate,data_filtered.log)
lm10= lm(new_cases~.-stringency_index-population_density-aged_65_older-cvd_death_rate,data_filtered)
lm10.sqrt = lm(new_cases~.-stringency_index-population_density-aged_65_older-cvd_death_rate,data_filtered.sqrt)
dev.new()
par(mfrow=c(2,2))
plot(lm10)
plot(lm10.log)
plot(lm10.sqrt)
vif(lm10)
vif(lm10.log)
vif(lm10.sqrt)
